name: RegCheck
main: de.zwinkie.regcheck.Main
version: 2.0
authors: [CyanLights, Aly9]
commands:
   check:
      description: Checks if a player registered on zwinkie.de.
      usage: /check [-f] <player>
      permission: regcheck.lookup
      permission-message: You don't have permission to use this command.
   dropan:
      description: Drops an anvil on a player
      usage: /dropan <player>
      permission: regcheck.lookup
      permission-message: You don't have permission to use this command.
permissions:
    regcheck.lookup:
        description: Allows you to check if a player has registered on zwinkie.de
        default: op